ApplicantName: Dr.~Lennart Wittkuhn
ApplicantUniversity: University of Hamburg
ApplicantInstitute: Institute of Psychology
ApplicantResearchGroup: Chair for Mechanisms of Learning and Change
ApplicantAddress: Von-Melle-Park 5, 20146 Hamburg
ApplicantEmailAddress: \href{mailto:lennart.wittkuhn@uni-hamburg.de}{lennart.wittkuhn@uni-hamburg.de}
ApplicantPhoneNumber: +49 040--42838 5346
ApplicantFaxNumber: not applicable
ProjectTitle: Version control of code and data using Git and DataLad
DateApplication: \today
ProjectLeaderName: Dr.~Lennart Wittkuhn
ProjectLeaderUniversity: University of Hamburg
ProjectLeaderInstitute: Institute of Psychology
ProjectLeaderResearchGroup: Chair for Mechanisms of Learning and Change
ProjectLeaderAddress: Von-Melle-Park 5, 20146 Hamburg
ProjectLeaderEmailAddress: \href{mailto:lennart.wittkuhn@uni-hamburg.de}{lennart.wittkuhn@uni-hamburg.de}
ProjectLeaderPhoneNumber: +49 040--42838 5346
ProjectLeaderFaxNumber: not applicable
InvestigatorName: Dr.~Lennart Wittkuhn
InvestigatorPhoneNumber: +49 040--42838 5346
InvestigatorEmailAddress: \href{mailto:lennart.wittkuhn@uni-hamburg.de}{lennart.wittkuhn@uni-hamburg.de}
